### ISSUE TITLE
Groupping no longer works

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/error-reporting-server#81]
Since CakePHP upgrade, groupping of incidents no longer works.

Eg: https://reports.phpmyadmin.net/reports/view/11887 show no group, ungroupping fails and there is no controls to group.

CC @smita786

**Comment by smita786** [comment]
Hi Michal,
Thanks for putting it in bug. If I'm not wrong, you mean the feature where you can mark one report same as (related to) others ? that is broken, I'm aware of it and 'll fix the same soon. 
But all the Incidents of a particular report should be shown with that report correctly, just to be clear :-).

**Comment by nijel** [comment]
Here is what I can see in the error log:

```
2015-07-13 13:33:08 Error: [Cake\Error\FatalErrorException] Call to a member function read() on boolean
Request URL: /reports/unmark_related_to/11887?url=reports%2Funmark_related_to%2F11887
Stack Trace:
#0 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', '/home/reports/e...', 159)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}
```

**Comment by lem9** [comment]
Not sure if this is another way to describe the problem, but all new incidents show this:
````
This report has been marked the same as the following reports: (). Remove from this group
````

**Comment by nijel** [comment]
Fixed by #97

**Comment by devenbansod** [comment]
Actually I think this has just been partially fixed, I am now able to get the UI for groupping but am getting 'An internal error has occured' when I try to mark one report same as other one ?

**Comment by nijel** [comment]
Just tried that and indeed it causes error:

```
2015-12-27 09:30:48 Error: [Cake\Error\FatalErrorException] Call to a member function read() on boolean
Request URL: /reports/mark_related_to/18049?url=reports%2Fmark_related_to%2F18049&related_to=18059
Stack Trace:
#0 /home/reports/error-reporting-server/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(92): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', '/home/reports/e...', 167)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}
```

**Comment by devenbansod** [comment]
Will look into it.
